on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: './stable/cerebro/' 
        helm-version: '2.11' 
      id: bake
